"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useSelector } from "react-redux";
import { toast } from "sonner";
import { bookingsApi } from "@/lib/api/bookings";
import { queryKeys } from "@/lib/query/keys";
import { selectAuthInitialized,selectIsAuthenticated } from "@/store/auth/selectors";
import type { BookingStatus } from "@/types";
const labels:Record<BookingStatus,string>={pending:"Pending",confirmed:"Confirmed",in_progress:"In progress",completed:"Completed",cancelled:"Cancelled"};
const colors:Record<BookingStatus,string>={pending:"bg-amber-100 text-amber-800",confirmed:"bg-blue-100 text-blue-800",in_progress:"bg-violet-100 text-violet-800",completed:"bg-green-100 text-green-800",cancelled:"bg-slate-200 text-slate-600"};
export function BookingHistory(){const authenticated=useSelector(selectIsAuthenticated),initialized=useSelector(selectAuthInitialized),params=useSearchParams(),client=useQueryClient(),created=params.get("created");const query=useQuery({queryKey:queryKeys.bookings,queryFn:bookingsApi.list,enabled:initialized&&authenticated});const cancel=useMutation({mutationFn:(id:string)=>bookingsApi.update(id,{status:"cancelled"}),onSuccess:()=>{client.invalidateQueries({queryKey:queryKeys.bookings});toast.success("Booking cancelled")},onError:()=>toast.error("Could not cancel this booking")});
if(!initialized)return <p>Checking your session…</p>;if(!authenticated)return <div className="rounded-3xl border bg-white p-10 text-center"><h2 className="text-2xl font-bold text-brand-navy">Sign in to see your bookings</h2><p className="mt-3 text-slate-600">Your booking history is private and only available in your account.</p><Link href="/login?next=%2Fbookings" className="mt-6 inline-block rounded-full bg-brand-navy px-6 py-3 font-semibold text-white">Sign in</Link></div>;if(query.isLoading)return <p>Loading your bookings…</p>;if(query.isError)return <p className="rounded-2xl bg-red-50 p-5 text-red-700">We could not load your bookings.</p>;const bookings=query.data??[];
return <div className="space-y-5">{created&&<div className="rounded-2xl border border-green-200 bg-green-50 p-5 text-green-900"><b>Your booking was received.</b> Keep this reference: <span className="font-mono font-bold">{created}</span></div>}{!bookings.length?<div className="rounded-3xl border bg-white p-10 text-center"><h2 className="text-2xl font-bold text-brand-navy">No bookings yet</h2><p className="mt-2 text-slate-600">When you schedule a service, you’ll be able to follow it here.</p><Link href="/book" className="mt-6 inline-block rounded-full bg-brand-green px-6 py-3 font-semibold text-white">Book a service</Link></div>:bookings.map(booking=><article key={booking.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-sm font-bold text-brand-green">{booking.reference}</p><h2 className="mt-1 text-xl font-bold text-brand-navy">{booking.service_name}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${colors[booking.status]}`}>{labels[booking.status]}</span></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Date and time</dt><dd className="mt-1 font-semibold">{new Date(`${booking.service_date}T${booking.service_time}`).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}</dd></div><div><dt className="text-slate-500">Location</dt><dd className="mt-1 font-semibold">{booking.location}</dd></div><div><dt className="text-slate-500">Contact</dt><dd className="mt-1 font-semibold">{booking.phone}</dd></div></dl>{booking.notes&&<p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">{booking.notes}</p>}{["pending","confirmed"].includes(booking.status)&&<button onClick={()=>cancel.mutate(booking.id)} disabled={cancel.isPending} className="mt-5 text-sm font-semibold text-red-600 hover:underline disabled:opacity-50">Cancel booking</button>}</article>)}</div>}
