"use client";
import { KeyboardEvent,useEffect,useId,useRef,useState } from "react";

type Suggestion={id:string;label:string;address:string;latitude?:number;longitude?:number};
type LocationAutocompleteProps={value:string;onChange:(value:string)=>void;label?:string;placeholder?:string;required?:boolean;disabled?:boolean;className?:string;countryCode?:string;onCoordinatesChange?:(latitude:number,longitude:number)=>void};

export function LocationAutocomplete({value,onChange,label="Location",placeholder="Start typing an address or area…",required=false,disabled=false,className="",countryCode="ug",onCoordinatesChange}:LocationAutocompleteProps){
 const id=useId(),containerRef=useRef<HTMLDivElement>(null),timerRef=useRef<ReturnType<typeof setTimeout>|null>(null),requestRef=useRef<AbortController|null>(null),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[active,setActive]=useState(0),[error,setError]=useState(false);
 const apiKey=process.env.NEXT_PUBLIC_GEOAPIFY_API_KEY;
 useEffect(()=>{const outside=(event:MouseEvent)=>{if(!containerRef.current?.contains(event.target as Node))setOpen(false)};document.addEventListener("mousedown",outside);return()=>{document.removeEventListener("mousedown",outside);if(timerRef.current)clearTimeout(timerRef.current);requestRef.current?.abort()}},[]);
 const search=(query:string)=>{if(timerRef.current)clearTimeout(timerRef.current);requestRef.current?.abort();if(query.trim().length<2){setSuggestions([]);setLoading(false);return}if(!apiKey){setError(true);return}setError(false);setLoading(true);timerRef.current=setTimeout(async()=>{const controller=new AbortController();requestRef.current=controller;try{const params=new URLSearchParams({text:query.trim(),apiKey,limit:"5",lang:"en",format:"geojson"});if(countryCode)params.set("filter",`countrycode:${countryCode}`);const response=await fetch(`https://api.geoapify.com/v1/geocode/autocomplete?${params}`,{signal:controller.signal});if(!response.ok)throw new Error();const data=await response.json() as {features?:Array<{properties?:{place_id?:string;formatted?:string;name?:string;street?:string;lat?:number;lon?:number}}>} ;const next=(data.features??[]).map((feature,index)=>{const item=feature.properties??{},address=item.formatted??"";return{id:item.place_id??`${address}-${index}`,label:item.name??item.street??address.split(",")[0],address,latitude:item.lat,longitude:item.lon}}).filter(item=>item.address);setSuggestions(next);setActive(0);setOpen(true)}catch(fetchError){if((fetchError as Error).name!=="AbortError"){setSuggestions([]);setError(true)}}finally{if(requestRef.current===controller)setLoading(false)}},350)};
 const type=(next:string)=>{onChange(next);setOpen(true);search(next)};
 const choose=(item:Suggestion)=>{onChange(item.address);setSuggestions([]);setOpen(false);if(item.latitude!==undefined&&item.longitude!==undefined)onCoordinatesChange?.(item.latitude,item.longitude)};
 const keyDown=(event:KeyboardEvent<HTMLInputElement>)=>{if(event.key==="ArrowDown"){event.preventDefault();setActive(index=>Math.min(suggestions.length-1,index+1))}if(event.key==="ArrowUp"){event.preventDefault();setActive(index=>Math.max(0,index-1))}if(event.key==="Enter"&&open&&suggestions[active]){event.preventDefault();choose(suggestions[active])}if(event.key==="Escape")setOpen(false)};
 return <div ref={containerRef} className={`relative ${className}`}>{label&&<label htmlFor={id} className="block text-sm font-semibold text-brand-navy">{label}{required&&<span className="text-red-500"> *</span>}</label>}<div className="relative mt-2"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="absolute left-3 top-3.5 h-5 w-5 text-slate-400"><path strokeLinecap="round" strokeLinejoin="round" d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg><input id={id} value={value} onChange={event=>type(event.target.value)} onFocus={()=>{if(value.length>=2)setOpen(true)}} onKeyDown={keyDown} required={required} disabled={disabled} autoComplete="street-address" placeholder={placeholder} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={`${id}-suggestions`} className="w-full rounded-xl border border-slate-300 bg-white py-3 pl-10 pr-10 outline-none transition focus:border-brand-green focus:ring-2 focus:ring-green-100 disabled:bg-slate-100"/>{loading&&<span aria-label="Searching locations" className="absolute right-3 top-3.5 h-5 w-5 animate-spin rounded-full border-2 border-slate-300 border-t-brand-green"/>}</div>{open&&value.trim().length>=2&&<div id={`${id}-suggestions`} role="listbox" className="absolute z-50 mt-2 max-h-72 w-full overflow-y-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-xl">{suggestions.map((item,index)=><button key={item.id} type="button" role="option" aria-selected={index===active} onMouseEnter={()=>setActive(index)} onClick={()=>choose(item)} className={`flex w-full items-start gap-3 rounded-xl px-3 py-3 text-left ${index===active?"bg-slate-100":"hover:bg-slate-50"}`}><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="mt-0.5 h-4 w-4 shrink-0 text-brand-green"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/></svg><span className="min-w-0"><span className="block font-semibold text-brand-navy">{item.label}</span><span className="mt-0.5 block text-xs text-slate-500">{item.address}</span></span></button>)}{!loading&&!suggestions.length&&!error&&<p className="px-3 py-5 text-center text-sm text-slate-500">No matching locations found. You can still use the address you entered.</p>}{error&&<p className="px-3 py-4 text-center text-sm text-slate-500">Suggestions are temporarily unavailable. You can still enter the address manually.</p>}</div>}</div>
}
