"use client";
import { ChangeEvent, DragEvent, useEffect, useRef, useState } from "react";

export function MultiPhotoUpload({files,onChange,maxFiles=5}:{files:File[];onChange:(files:File[])=>void;maxFiles?:number}){
  const inputRef=useRef<HTMLInputElement>(null),[dragging,setDragging]=useState(false),[previews,setPreviews]=useState<string[]>([]);
  useEffect(()=>{const urls=files.map(file=>URL.createObjectURL(file));setPreviews(urls);return()=>urls.forEach(URL.revokeObjectURL)},[files]);
  const add=(incoming:File[])=>{const images=incoming.filter(file=>file.type.startsWith("image/")&&file.size<=5*1024*1024);onChange([...files,...images].slice(0,maxFiles))};
  const choose=(event:ChangeEvent<HTMLInputElement>)=>{add(Array.from(event.target.files??[]));event.target.value=""};
  const drop=(event:DragEvent<HTMLDivElement>)=>{event.preventDefault();setDragging(false);add(Array.from(event.dataTransfer.files))};
  return <div className="sm:col-span-2"><div className="mb-2 flex items-center justify-between"><p className="text-sm font-semibold text-brand-navy">Property photos <span className="font-normal text-slate-400">(optional)</span></p><span className="text-xs text-slate-500">{files.length}/{maxFiles}</span></div><div role="button" tabIndex={0} onKeyDown={event=>{if(event.key==="Enter"||event.key===" ")inputRef.current?.click()}} onClick={()=>inputRef.current?.click()} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop} className={`grid cursor-pointer place-items-center rounded-2xl border-2 border-dashed p-7 text-center transition ${dragging?"border-brand-green bg-green-50":"border-slate-300 bg-slate-50 hover:border-brand-green"}`}><input ref={inputRef} type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={choose} className="sr-only" disabled={files.length>=maxFiles}/><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-9 w-9 text-brand-green"><path strokeLinecap="round" strokeLinejoin="round" d="M12 16V4m0 0L7 9m5-5 5 5M5 14v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-5"/></svg><p className="mt-2 font-semibold text-brand-navy">Click to upload or drag and drop</p><p className="mt-1 text-xs text-slate-500">JPG, PNG or WebP · maximum 5 MB each · up to 5 photos</p></div>{files.length>0&&<div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5">{files.map((file,index)=><div key={`${file.name}-${file.lastModified}`} className="group relative overflow-hidden rounded-xl border bg-white"><img src={previews[index]} alt={file.name} className="aspect-square w-full object-cover"/><button type="button" onClick={()=>onChange(files.filter((_,item)=>item!==index))} aria-label={`Remove ${file.name}`} className="absolute right-1.5 top-1.5 grid h-7 w-7 place-items-center rounded-full bg-black/70 text-white">×</button><p className="truncate px-2 py-1.5 text-xs" title={file.name}>{file.name}</p></div>)}</div>}</div>
}
