# Generated starter migration for Nasse boilerplate.
import uuid
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
      migrations.CreateModel(name='Service',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=120)),('slug',models.SlugField(unique=True)),('category',models.CharField(choices=[('RESIDENTIAL','Residential'),('COMMERCIAL','Commercial'),('POST_CONSTRUCTION','Post-construction'),('FACILITY_CARE','Facility care')],max_length=32)),('short_description',models.CharField(max_length=240)),('description',models.TextField(blank=True)),('is_active',models.BooleanField(default=True))]),
      migrations.CreateModel(name='CorporateEnquiry',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company_name',models.CharField(max_length=180)),('contact_name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(max_length=40)),('facility_type',models.CharField(blank=True,max_length=120)),('location',models.CharField(blank=True,max_length=180)),('approximate_size',models.CharField(blank=True,max_length=120)),('frequency',models.CharField(blank=True,max_length=80)),('preferred_start_date',models.DateField(blank=True,null=True)),('requirements',models.TextField(blank=True)),('status',models.CharField(default='NEW',max_length=30))]),
      migrations.CreateModel(name='ContactMessage',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(blank=True,max_length=40)),('message',models.TextField()),('is_resolved',models.BooleanField(default=False))]),
      migrations.CreateModel(name='QuoteRequest',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('full_name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(max_length=40)),('location',models.CharField(max_length=180)),('property_type',models.CharField(blank=True,max_length=120)),('approximate_size',models.CharField(blank=True,max_length=120)),('preferred_date',models.DateField(blank=True,null=True)),('frequency',models.CharField(blank=True,max_length=50)),('notes',models.TextField(blank=True)),('status',models.CharField(choices=[('NEW','New'),('CONTACTED','Contacted'),('QUOTED','Quoted'),('ACCEPTED','Accepted'),('DECLINED','Declined')],default='NEW',max_length=20)),('service',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='quotes',to='cleaning.service'))]),
    ]
