# Generated by Django 5.2.17 on 2026-09-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_seed_cleaning_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='corporateenquiry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='user',
        ),
    ]
