# Generated by Django 5.2.17 on 2026-09-02 13:01

import uuid
import cleaning.models
from django.db import migrations, models

def populate_references(apps, schema_editor):
    QuoteRequest = apps.get_model("cleaning", "QuoteRequest")
    for quote in QuoteRequest.objects.filter(reference__isnull=True):
        quote.reference = f"NAS-Q-{uuid.uuid4().hex[:8].upper()}"
        quote.save(update_fields=("reference",))


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0006_booking_quote_quoterequest_admin_notes_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="quoterequest",
            name="reference",
            field=models.CharField(default=cleaning.models.generate_quote_reference, editable=False, max_length=24, unique=True),
        ),
    ]
