# Generated by Django 5.2.17 on 2026-09-03 14:42

from django.db import migrations

def seed_areas(apps, schema_editor):
    ServiceArea=apps.get_model("cleaning","ServiceArea")
    areas=(
        ("Kampala","kampala","active","Full residential and commercial cleaning coverage across Kampala.",0),
        ("Wakiso","wakiso","active","Serving Wakiso, including the greater Kampala metropolitan area.",15000),
        ("Mukono","mukono","active","Scheduled residential and commercial cleaning is available in Mukono.",20000),
        ("Jinja","jinja","coming_soon","Our Jinja cleaning team is coming soon.",30000),
        ("Mbarara","mbarara","inactive","Service is not currently available in Mbarara.",40000),
    )
    for name,slug,status,description,charge in areas:
        ServiceArea.objects.update_or_create(slug=slug,defaults={"name":name,"status":status,"description":description,"transport_charge":charge})


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0008_areainterest_servicearea_booking_service_area_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_areas,migrations.RunPython.noop),
    ]
