"use client";
import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { quotesApi } from "@/lib/api/quotes";
import { queryKeys } from "@/lib/query/keys";
import type { QuoteRequest } from "@/types";
import { FormattedNumberInput } from "@/components/common/formatted-number-input";
import { RichTextEditor } from "@/components/common/rich-text-editor";
import { RichTextContent } from "@/components/common/rich-text-content";
const input="mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-brand-green";
export default function QuotesPage(){const client=useQueryClient();const query=useQuery({queryKey:queryKeys.quotes,queryFn:quotesApi.adminList});const mutation=useMutation({mutationFn:({id,payload}:{id:string;payload:Parameters<typeof quotesApi.update>[1]})=>quotesApi.update(id,payload),onSuccess:()=>{client.invalidateQueries({queryKey:queryKeys.quotes});toast.success("Estimate sent to customer")},onError:()=>toast.error("Enter a valid estimated price before sending")});return <div><h1 className="text-3xl font-bold text-brand-navy">Estimate Requests</h1><p className="mt-2 text-slate-600">Review property details and photos, then send a price to the customer.</p><div className="mt-7 space-y-6">{query.data?.map(quote=><EstimateReview key={quote.id} quote={quote} saving={mutation.isPending} onSend={(payload)=>mutation.mutate({id:quote.id,payload})}/>)}</div>{!query.isLoading&&!query.data?.length&&<p className="mt-8 rounded-2xl bg-white p-8 text-center">No estimate requests.</p>}</div>}
function EstimateReview({quote,saving,onSend}:{quote:QuoteRequest;saving:boolean;onSend:(payload:Parameters<typeof quotesApi.update>[1])=>void}){const [price,setPrice]=useState(quote.estimated_price??""),[notes,setNotes]=useState(quote.admin_notes??"");return <article className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex flex-wrap justify-between gap-4 border-b bg-slate-50 p-6"><div><p className="font-mono text-sm font-bold text-brand-green">REQUEST #{quote.reference}</p><h2 className="mt-1 text-xl font-bold">{quote.full_name}</h2><p className="text-sm text-slate-500">{quote.email} · {quote.phone}</p></div><span className="h-fit rounded-full bg-white px-4 py-2 text-sm font-bold shadow-sm">{quote.status.replaceAll("_"," ")}</span></div><div className="grid gap-7 p-6 lg:grid-cols-[3fr_2fr]"><div><dl className="grid gap-4 text-sm sm:grid-cols-2"><Info label="Service" value={quote.service_name}/><Info label="Property" value={`${quote.bedrooms??0} Bedroom ${quote.property_type} · ${quote.bathrooms??0} bathrooms`}/><Info label="Location" value={quote.location}/><Info label="Preferred schedule" value={`${quote.preferred_date} · ${quote.preferred_time?.slice(0,5)}`}/></dl><h3 className="mt-6 text-sm font-bold">Photos ({quote.photos.length})</h3>{quote.photos.length?<div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{quote.photos.map(photo=><a key={photo.id} href={photo.file} target="_blank" rel="noreferrer" className="group"><img src={photo.file} alt={photo.original_name} className="aspect-square w-full rounded-xl object-cover transition group-hover:opacity-90"/><p className="mt-1 truncate text-xs text-slate-500">{photo.original_name}</p></a>)}</div>:<p className="mt-2 text-sm text-slate-500">No photos uploaded.</p>}<h3 className="mt-6 text-sm font-bold">Customer notes</h3>{quote.notes?<RichTextContent html={quote.notes} className="mt-2 rounded-xl bg-slate-50 p-4 text-sm text-slate-700"/>:<p className="mt-2 text-sm text-slate-500">No additional notes.</p>}</div><div className="rounded-2xl border p-5"><label className="text-sm font-bold">Estimated Price (UGX)<FormattedNumberInput className={input} min={1} step={1000} required value={price} onValueChange={value=>setPrice(value?String(value):"")} placeholder="180,000"/></label><RichTextEditor className="mt-5" label="Admin notes" value={notes} onChange={setNotes} placeholder="Approximately 5 hours, 2 cleaners required." minHeight="120px"/><button disabled={saving||!price||quote.status==="ACCEPTED"} onClick={()=>onSend({estimated_price:price,admin_notes:notes,status:"QUOTED"})} className="mt-5 w-full rounded-xl bg-brand-navy px-5 py-3 font-bold text-white disabled:opacity-50">{quote.status==="QUOTED"?"Update and resend quote":"Send quote"}</button></div></div></article>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
